import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { buildKeyTurns, buildReplayCurves } from "../src/replay/analysis.ts";
import { boundedFinalRoundSensitivity, diagnoseRun } from "../src/replay/diagnosis.ts";
import { buildRunEvidenceGraph } from "../src/replay/evidence.ts";
import { createGameServer } from "../src/server.ts";
import { GameStore } from "../src/storage.ts";
import { TeamHost } from "../src/team/engine.ts";
import { FixtureTeamProvider } from "../src/team/providers.ts";
async function run(caseId:string,strategy:"security-contain"|"engineer-seal",store=new GameStore(":memory:")){const runId=`run:diagnosis:${caseId}:${strategy}`;store.createRun({runId,scenarioVersion:2,scenarioCaseId:caseId,rulesetVersion:3});const host=new TeamHost(store,new FixtureTeamProvider({breachStrategy:strategy}));await host.run(runId,512);return{store,runId};}
async function listen(game:ReturnType<typeof createGameServer>){await new Promise<void>(resolve=>game.server.listen(0,"127.0.0.1",resolve));const address=game.server.address();if(!address||typeof address==="string")throw new Error("no address");return`http://127.0.0.1:${address.port}`;}
test("curves contain exactly one point per revision and conserve items",async()=>{const{store,runId}=await run("baseline","security-contain");try{const graph=buildRunEvidenceGraph(store,runId),curves=buildReplayCurves(store,runId,graph);assert.equal(curves.revisions.length,19);assert.deepEqual(curves.revisions,Array.from({length:19},(_,i)=>i));for(const points of [curves.battery,curves.oxygen,curves.reactorHeat,...Object.values(curves.actorHealth),...Object.values(curves.crewHealth),...Object.values(curves.systems),...Object.values(curves.items),...Object.values(curves.objectives)])assert.equal(points.length,19);for(const points of Object.values(curves.items)){assert.equal(new Set(points.map(point=>point.total)).size,1);}assert.equal(buildReplayCurves(store,runId,graph).curvesDigest,curves.curvesDigest);}finally{store.close();}});
test("victory diagnosis is direct, evidence-linked, deterministic, and bounded",async()=>{const{store,runId}=await run("baseline","security-contain");try{const first=diagnoseRun(store,runId),second=diagnoseRun(store,runId);assert.deepEqual(second,first);assert.equal(first.terminal.status,"victory");assert.equal(first.terminal.reason,"rescue_signal_verified");assert.equal(first.claims[0]?.evidenceClass,"VERIFIED_DIRECT");assert.ok(first.claims[0]?.evidenceNodeIds.every(id=>id.startsWith("world-")));assert.ok(first.keyTurns.length<=12);assert.ok(first.keyTurns.some(turn=>turn.kind==="terminal"&&turn.revision===first.terminal.revision));assert.ok(first.keyTurns.some(turn=>turn.kind==="objective"&&/distress|rescue/i.test(turn.title)));assert.ok(first.claims.some(claim=>claim.evidenceClass==="CONTEXT_ONLY"&&/counterfactual/.test(claim.title)));}finally{store.close();}});
test("power exhaustion reports direct predicate and verified battery contributors without singular causality",async()=>{const{store,runId}=await run("power-constrained","engineer-seal");try{const diagnosis=diagnoseRun(store,runId);assert.equal(diagnosis.terminal.status,"failure");assert.equal(diagnosis.terminal.reason,"power_exhausted");assert.match(diagnosis.claims.find(c=>c.evidenceClass==="VERIFIED_DIRECT")?.title??"",/Battery/);assert.ok(diagnosis.claims.some(c=>c.evidenceClass==="VERIFIED_CONTRIBUTOR"&&/Battery reserve/.test(c.title)));assert.ok(diagnosis.claims.filter(c=>c.evidenceClass!=="CONTEXT_ONLY").every(c=>c.evidenceNodeIds.length>0));const sensitive=boundedFinalRoundSensitivity(store,runId);assert.deepEqual(diagnosis.claims.filter(c=>c.evidenceClass==="COUNTERFACTUAL_SENSITIVE"),sensitive);assert.equal(diagnosis.unsupportedCounterfactualReason===null,sensitive.length>0);}finally{store.close();}});
test("oxygen-constrained failure reports health and oxygen contributors",async()=>{const{store,runId}=await run("oxygen-constrained","engineer-seal");try{const diagnosis=diagnoseRun(store,runId);assert.equal(diagnosis.terminal.reason,"team_incapacitated");assert.ok(diagnosis.claims.some(c=>/Oxygen loss/.test(c.title)));assert.ok(diagnosis.claims.some(c=>/lost health/.test(c.title)));assert.ok(diagnosis.keyTurns.some(turn=>turn.kind==="health-threshold"));}finally{store.close();}});
test("running mission diagnosis never invents a terminal failure",()=>{const store=new GameStore(":memory:");try{const diagnosis=diagnoseRun(store);assert.equal(diagnosis.terminal.status,"running");assert.equal(diagnosis.claims.some(c=>c.evidenceClass==="VERIFIED_DIRECT"),false);assert.ok(diagnosis.claims.some(claim=>/Mission remains active/.test(claim.title)));}finally{store.close();}});
test("analysis and diagnosis HTTP APIs are read-only",async()=>{const directory=mkdtempSync(join(tmpdir(),"ordivon-diagnosis-http-"));const game=createGameServer({dbPath:join(directory,"world.sqlite3"),teamProviderFactory:()=>new FixtureTeamProvider()});try{const runId="run:diagnosis:http";game.store.createRun({runId,scenarioVersion:2,scenarioCaseId:"baseline",rulesetVersion:3});await new TeamHost(game.store,new FixtureTeamProvider()).run(runId,512);const before=game.store.eventCount(runId),base=await listen(game);const analysis=await fetch(`${base}/api/replay/analysis?runId=${runId}`);assert.equal(analysis.status,200);const a=await analysis.json() as any;assert.equal(a.curves.revisions.length,19);assert.ok(a.keyTurns.length<=12);const response=await fetch(`${base}/api/replay/diagnosis?runId=${runId}`);assert.equal(response.status,200);const diagnosis=await response.json() as any;assert.equal(diagnosis.terminal.status,"victory");assert.equal(game.store.eventCount(runId),before);}finally{await game.close();rmSync(directory,{recursive:true,force:true});}});
