const app=document.querySelector('#app');const status=document.querySelector('#status');
const model={catalog:null,runs:[],view:null,runId:new URL(location.href).searchParams.get('runId'),busy:false,error:null};
const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function request(path,options={}){const response=await fetch(path,{headers:{'content-type':'application/json',...(options.headers||{})},...options});const body=await response.json();if(!response.ok)throw new Error(body.message||body.error||`HTTP ${response.status}`);return body}
const api={catalog:()=>request('/api/casefile/catalog'),runs:()=>request('/api/casefile/runs'),create:(runId,scenarioId)=>request('/api/casefile/runs',{method:'POST',body:JSON.stringify({runId,scenarioId})}),state:(runId)=>request(`/api/casefile/state?runId=${encodeURIComponent(runId)}`),act:(runId,actionId)=>request(`/api/casefile/action?runId=${encodeURIComponent(runId)}`,{method:'POST',body:JSON.stringify({actionId})})};
function announce(text){if(!status)return;status.textContent='';requestAnimationFrame(()=>status.textContent=text)}
function updateUrl(runId){const url=new URL(location.href);if(runId)url.searchParams.set('runId',runId);else url.searchParams.delete('runId');history.replaceState({},'',url)}
async function perform(label,fn){model.busy=true;model.error=null;render();announce(label);try{await fn()}catch(error){console.error(error);model.error=error.message||String(error)}finally{model.busy=false;render()}}
function freshRunId(scenarioId){return `case:${scenarioId}:${Date.now().toString(36)}`}
function landing(){return `<div class="shell"><section class="landing-head"><p class="eyebrow">Ordivon Game · G6 candidate</p><h1>Casefile</h1><p class="lede">Small incidents. Partial testimony. Limited time. Build a theory from what people say and what the scene can actually support, then commit one accusation.</p></section><div class="section-title"><div><p class="eyebrow">available incidents</p><h2>Choose a case</h2></div></div><section class="case-grid">${model.catalog.scenarios.map(c=>`<article class="case-card"><div><p class="eyebrow">${esc(c.scenarioId)}</p><h3>${esc(c.title)}</h3><p>${esc(c.hook)}</p></div><button data-start="${esc(c.scenarioId)}">Open case</button></article>`).join('')}</section>${model.runs.length?`<div class="section-title"><div><p class="eyebrow">retained investigations</p><h2>Resume</h2></div></div><section class="run-grid">${model.runs.slice(0,9).map(r=>`<article class="run-card"><div><strong>${esc(r.runId)}</strong><small>${esc(r.scenarioId)} · revision ${esc(r.revision)} · ${esc(r.status)}</small></div><button data-resume="${esc(r.runId)}">Resume</button></article>`).join('')}</section>`:''}</div>`}
function statementLabel(entry,people){if(entry.kind==='system')return 'CASE';if(entry.kind==='trace')return 'TRACE';const person=people.find(p=>p.personId===entry.speakerId);return `${person?.name||entry.speakerId} · ${entry.kind==='confrontation'?'CONFRONTED':'TESTIMONY'}`}
function statements(view){return `<section class="panel"><p class="eyebrow">investigation record</p><h2>What you actually learned</h2><div class="statement-list">${[...view.statements].reverse().map(entry=>`<article class="statement ${esc(entry.kind)}"><span>${esc(statementLabel(entry,view.people))} · #${esc(entry.sequence)}</span>${esc(entry.text)}</article>`).join('')}</div></section>`}
function actionGroup(view,kind,title,cls=''){const actions=view.actions.filter(a=>a.kind===kind);if(!actions.length)return'';return `<div class="action-group"><h3>${esc(title)}</h3><div class="action-buttons ${cls}">${actions.map(a=>`<button data-case-action="${esc(a.actionId)}">${esc(a.label)}${a.cost?`<br><small>cost ${a.cost} move</small>`:''}</button>`).join('')}</div></div>`}
function terminal(view){if(!view.outcome)return'';return `<section class="panel terminal ${view.outcome.correct?'correct':'wrong'}" data-testid="casefile-terminal"><div class="terminal-result"><div><p class="eyebrow">case closed</p><h2>${view.outcome.correct?'Accusation confirmed':'Wrong accusation'}</h2><p>You accused <strong>${esc(view.outcome.accusedPersonName)}</strong>. Responsible: <strong>${esc(view.outcome.culpritName)}</strong>.</p></div><button data-new-case>New case</button></div><div class="reconstruction"><p class="eyebrow">reconstruction</p><p>${esc(view.outcome.reconstruction)}</p><p><strong>Motive:</strong> ${esc(view.outcome.motive)}</p></div></section>`}
function investigation(view){return `<div class="shell" data-case-revision="${esc(view.run.revision)}"><header class="topbar"><div><p class="eyebrow">Casefile · ${esc(view.run.scenarioId)}</p><h1>${esc(view.case.title)}</h1><p class="lede">${esc(view.case.hook)}</p></div><div class="clock"><strong>${esc(view.run.movesRemaining)}</strong><small>investigation moves left</small></div></header><section class="brief"><strong>Assignment</strong><br>${esc(view.case.setup)}</section>${terminal(view)}<section class="investigation"><div class="stack"><section class="panel"><p class="eyebrow">scene evidence</p><h2>Traces</h2><div class="trace-grid">${view.traces.map(trace=>`<article class="trace ${trace.inspected?'inspected':''}"><span>${esc(trace.location)}</span><strong>${esc(trace.label)}</strong>${trace.inspected?`<p>${esc(trace.clue)}</p>`:'<p class="unknown">Not inspected.</p>'}</article>`).join('')}</div></section><section class="panel"><p class="eyebrow">crew</p><h2>People</h2><div class="people-grid">${view.people.map(person=>`<article class="person"><span>${esc(person.role)}</span><strong>${esc(person.name)}</strong><small>questioned ${esc(person.questioned)} / 2</small>${person.lastStatement?`<p>“${esc(person.lastStatement)}”</p>`:'<p class="muted">No statement yet.</p>'}</article>`).join('')}</div></section>${view.run.status==='investigating'?`<section class="panel"><p class="eyebrow">your next move</p><h2>Investigate or commit</h2>${actionGroup(view,'inspect','Inspect a trace')}${actionGroup(view,'question','Question someone')}${actionGroup(view,'confront','Confront with evidence','confront')}${actionGroup(view,'accuse','Commit accusation','accuse')}</section>`:''}</div>${statements(view)}</section></div>`}
function render(){if(!model.catalog){app.innerHTML='<div class="shell"><p>Loading Casefile…</p></div>';return}app.innerHTML=model.view?investigation(model.view):landing();bind();if(model.busy)app.insertAdjacentHTML('beforeend','<div class="busy"><div>Updating the case…</div></div>');if(model.error)app.insertAdjacentHTML('beforeend',`<div class="toast" role="alert">${esc(model.error)}</div>`)}
function bind(){document.querySelectorAll('[data-start]').forEach(button=>button.onclick=()=>{const scenarioId=button.dataset.start;const runId=freshRunId(scenarioId);perform('Opening case',async()=>{model.view=await api.create(runId,scenarioId);model.runId=runId;updateUrl(runId);model.runs=(await api.runs()).runs})});document.querySelectorAll('[data-resume]').forEach(button=>button.onclick=()=>perform('Recovering investigation',async()=>{model.runId=button.dataset.resume;model.view=await api.state(model.runId);updateUrl(model.runId)}));document.querySelectorAll('[data-case-action]').forEach(button=>button.onclick=()=>perform('Applying investigation move',async()=>{model.view=await api.act(model.runId,button.dataset.caseAction);announce(model.view.outcome?'Case closed':`${model.view.run.movesRemaining} moves remain`) }));document.querySelectorAll('[data-new-case]').forEach(button=>button.onclick=()=>{model.view=null;model.runId=null;updateUrl(null);render()})}
async function boot(){try{const [catalog,runs]=await Promise.all([api.catalog(),api.runs()]);model.catalog=catalog;model.runs=runs.runs;if(model.runId)model.view=await api.state(model.runId)}catch(error){model.error=error.message||String(error)}render()}boot();
