const app=document.querySelector('#app');
const STORAGE='ordivon-pre-g0-c0-v1';
const packets=[
 {id:'A',name:'PGP-A Precision Traversal',center:'embodied mastery'},
 {id:'D',name:'PGP-D Investigation',center:'knowledge / inference'},
 {id:'I',name:'PGP-I Creation / Expression',center:'authorship'},
];
let packet='A';
let participant='local-c0';
let session=loadSession();
let stateA=newA();
let stateD=newD();
let stateI=newI();
function loadSession(){try{return JSON.parse(localStorage.getItem(STORAGE))||{schemaVersion:1,participant:'local-c0',sessions:[]}}catch{return{schemaVersion:1,participant:'local-c0',sessions:[]}}}
function persist(){session.participant=participant;localStorage.setItem(STORAGE,JSON.stringify(session));}
function rec(kind,data={}){const item={at:new Date().toISOString(),packet:`PGP-${packet}`,kind,...data};session.sessions.push(item);persist();return item}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function metric(k,v,d=''){return `<div class="metric"><span>${esc(k)}</span><strong>${esc(v)}</strong>${d?`<small>${esc(d)}</small>`:''}</div>`}
function logHtml(log){return `<div class="panel"><p class="eyebrow">local session trace</p><div class="log">${log.slice().reverse().map(x=>`<article class="${x.tone||''}"><small>${esc(x.tag||'event')}</small>${esc(x.text)}</article>`).join('')||'<p class="note">No events yet.</p>'}</div></div>`}
function newA(){return{room:0,attempt:1,deaths:0,completed:[],x:38,y:288,vx:0,vy:0,ground:false,start:performance.now(),keys:new Set(),raf:null,log:[{tag:'start',text:'Room 1 ready. Learn movement; no score or reward layer.'}]};}
const rooms=[
 {name:'Direct gap',spawn:[38,288],goal:[630,258,48,62],platforms:[[0,350,250,50],[330,330,390,70]]},
 {name:'Timing gate',spawn:[38,288],goal:[640,218,45,62],platforms:[[0,350,220,50],[280,310,150,30],[500,280,220,120]],hazard:[235,345,35,20]},
 {name:'Safe vs fast line',spawn:[38,288],goal:[650,170,45,62],platforms:[[0,350,170,50],[220,315,120,30],[385,270,125,30],[555,230,165,170],[180,370,390,30]],hazard:[345,340,35,30]},
];
function rectHit(ax,ay,aw,ah,b){return ax<b[0]+b[2]&&ax+aw>b[0]&&ay<b[1]+b[3]&&ay+ah>b[1]}
function resetA(death=false){const r=rooms[stateA.room];stateA.x=r.spawn[0];stateA.y=r.spawn[1];stateA.vx=0;stateA.vy=0;stateA.ground=false;if(death){stateA.deaths++;stateA.attempt++;stateA.start=performance.now();stateA.log.push({tag:`attempt ${stateA.attempt}`,tone:'warn',text:'Reset after a miss. Predict what you will change before retrying.'});rec('retry',{room:stateA.room+1,attempt:stateA.attempt});}}
function stepA(){const s=stateA,r=rooms[s.room];const left=s.keys.has('ArrowLeft')||s.keys.has('KeyA'),right=s.keys.has('ArrowRight')||s.keys.has('KeyD');s.vx+=(right?0.55:0)-(left?0.55:0);s.vx*=.82;s.vx=Math.max(-5,Math.min(5,s.vx));if((s.keys.has('Space')||s.keys.has('ArrowUp'))&&s.ground){s.vy=-9.5;s.ground=false}s.vy=Math.min(12,s.vy+.48);const prevY=s.y;s.x+=s.vx;s.y+=s.vy;s.x=Math.max(0,Math.min(696,s.x));s.ground=false;for(const p of r.platforms){if(rectHit(s.x,s.y,24,32,p)&&prevY+32<=p[1]+5&&s.vy>=0){s.y=p[1]-32;s.vy=0;s.ground=true}}if(s.y>410||(r.hazard&&rectHit(s.x,s.y,24,32,r.hazard))){resetA(true)}if(rectHit(s.x,s.y,24,32,r.goal)){const elapsed=Math.round(performance.now()-s.start);s.completed.push({room:s.room+1,attempt:s.attempt,elapsedMs:elapsed});s.log.push({tag:`room ${s.room+1}`,text:`Completed ${r.name} on attempt ${s.attempt} in ${(elapsed/1000).toFixed(1)}s.`});rec('room-complete',{room:s.room+1,attempt:s.attempt,elapsedMs:elapsed});if(s.room<rooms.length-1){s.room++;s.attempt=1;s.start=performance.now();const nr=rooms[s.room];s.x=nr.spawn[0];s.y=nr.spawn[1];s.vx=s.vy=0}else{s.log.push({tag:'apparatus',text:'All three rooms complete. Mechanical completion is not C0/C1 Player Value evidence.'});s.room=0;s.attempt=1;s.start=performance.now();resetA(false)}}drawA();s.raf=requestAnimationFrame(stepA)}
function drawA(){const c=document.querySelector('#traversal');if(!c)return;const ctx=c.getContext('2d'),r=rooms[stateA.room];c.dataset.room=String(stateA.room+1);c.dataset.playerX=stateA.x.toFixed(2);c.dataset.ground=String(stateA.ground);c.dataset.attempt=String(stateA.attempt);const liveRoom=document.querySelector('[data-a-room]'),liveAttempt=document.querySelector('[data-a-attempt]'),liveDeaths=document.querySelector('[data-a-deaths]'),liveCompleted=document.querySelector('[data-a-completed]');if(liveRoom)liveRoom.textContent=`${stateA.room+1}/3 · ${r.name}`;if(liveAttempt)liveAttempt.textContent=String(stateA.attempt);if(liveDeaths)liveDeaths.textContent=String(stateA.deaths);if(liveCompleted)liveCompleted.textContent=String(stateA.completed.length);ctx.clearRect(0,0,720,405);ctx.fillStyle='#080d14';ctx.fillRect(0,0,720,405);ctx.fillStyle='#263448';for(const p of r.platforms)ctx.fillRect(...p);if(r.hazard){ctx.fillStyle='#f17b74';ctx.fillRect(...r.hazard)}ctx.fillStyle='#79e0c5';ctx.fillRect(...r.goal);ctx.fillStyle='#92aaff';ctx.fillRect(stateA.x,stateA.y,24,32);ctx.fillStyle='#96a3b7';ctx.font='14px monospace';ctx.fillText(`Room ${stateA.room+1}: ${r.name}`,14,22)}
function bindA(){const kd=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','Space','KeyA','KeyD'].includes(e.code)){e.preventDefault();stateA.keys.add(e.code)}};const ku=e=>stateA.keys.delete(e.code);window.onkeydown=kd;window.onkeyup=ku;cancelAnimationFrame(stateA.raf);stateA.raf=requestAnimationFrame(stepA);document.querySelector('[data-reset-a]').onclick=()=>{stateA.log.push({tag:'manual reset',text:'Player requested a fresh traversal seed/session.'});rec('manual-reset');stateA=newA();render()}}
function renderA(){const r=rooms[stateA.room];return `<section class="grid"><div class="panel"><p class="eyebrow">PGP-A · embodied mastery · Runtime Agent none</p><h2>Precision Traversal</h2><p>Use <strong>A/D or ←/→</strong> and <strong>Space/↑</strong>. Reset is immediate; no score, collectibles, progression or story.</p><div class="metrics"><div class="metric"><span>room</span><strong data-a-room>${stateA.room+1}/3 · ${r.name}</strong></div><div class="metric"><span>attempt</span><strong data-a-attempt>${stateA.attempt}</strong></div><div class="metric"><span>miss resets</span><strong data-a-deaths>${stateA.deaths}</strong></div><div class="metric"><span>completed</span><strong data-a-completed>${stateA.completed.length}</strong></div></div><canvas id="traversal" width="720" height="405"></canvas><div class="controls"><button data-reset-a>Reset traversal session</button></div><div class="question"><strong>C1 mechanism question (ask after real play)</strong><p>Did you feel you were learning the movement itself? What changed in how you played?</p></div><p class="note">Automation proves input/collision/reset/goal usability only. C0/C1 player evidence is still unobserved; improvement, flow, self-attribution and voluntary retry require human evidence.</p></div>${logHtml(stateA.log)}</section>`}
const clues=[
 ['Badge log','Mara entered Archive at 20:51. The same badge crossed Relay Corridor at 21:06, then returned to Archive at 21:18.'],
 ['Coolant fiber','Blue coolant fiber is caught under the sabotaged relay cover. Lab and Maintenance both use this stock.'],
 ['Tool checkout','Ivo signed out a T-9 ratchet at 19:40. The relay cover has T-9 scoring, but the tool rack is shared during emergency drills.'],
 ['Camera reflection','A reflection shows a red sleeve near Relay Corridor at 21:07. Nera wears red; Archive emergency jackets are also red.'],
 ['Terminal heartbeat','Archive terminal activity at 21:09 used Mara’s session token, but its keyboard sensor recorded no local typing from 21:03–21:14.'],
 ['Door latency','Archive→Relay travel is 70–90 seconds. Lab→Relay is 4 minutes because Deck C lift was locked from 21:00–21:12.'],
];
const hyps=[['mara','Mara left Archive, sabotaged the relay, and kept her Archive session alive remotely.'],['sol','Sol used shared Lab coolant stock and crossed from Lab to Relay.'],['ivo','Ivo used the signed-out T-9 tool to sabotage the relay.']];
function newD(){return{revealed:new Set(),hyp:'',mechanism:'',submitted:false,log:[{tag:'case',text:'Relay sabotage occurred at 21:10. Three hypotheses are initially live.'}]}}
function revealD(i){if(stateD.submitted||stateD.revealed.has(i))return;stateD.revealed.add(i);stateD.log.push({tag:`evidence ${i+1}`,text:clues[i][1]});rec('evidence-reveal',{evidence:i+1});render()}
function submitD(){const text=document.querySelector('#mechanism')?.value.trim()||'';const h=document.querySelector('input[name=hyp]:checked')?.value||'';if(!h||text.length<12)return;stateD.hyp=h;stateD.mechanism=text;stateD.submitted=true;const correct=h==='mara'&&stateD.revealed.has(0)&&stateD.revealed.has(4)&&stateD.revealed.has(5);stateD.log.push({tag:'determination',tone:correct?'':'warn',text:`Committed ${h.toUpperCase()}: ${text}`});rec('determination',{hypothesis:h,mechanism:text,revealed:[...stateD.revealed],structuralCorrect:correct});render()}
function renderD(){const result=stateD.submitted?`<div class="outcome"><strong>Sealed case result</strong><p>${stateD.hyp==='mara'?'Mara sabotaged the relay. Badge corridor timing + remote session heartbeat + feasible Archive travel jointly explain how the apparent Archive alibi was manufactured.':'The sealed relay record clears that hypothesis. Mara was responsible; the decisive relation requires combining corridor timing, remote session evidence and route feasibility.'}</p><p class="note">A correct culprit without a causal explanation is not a positive PGP-D mechanism result.</p></div>`:'';return `<section class="grid"><div class="panel"><p class="eyebrow">PGP-D · knowledge / inference · Runtime Agent none</p><h2>Relay Case: causal reconstruction</h2><p>Reveal evidence in any order. Do not treat highlighted provenance as a solution hint: several clues are intentionally compatible with more than one hypothesis.</p><div class="metrics">${metric('evidence',`${stateD.revealed.size}/6`)}${metric('hypotheses',3)}${metric('answer revealed',stateD.submitted?'yes':'no')}${metric('mode','authored')}</div><div class="evidence-grid">${clues.map((c,i)=>`<div class="evidence-card ${stateD.revealed.has(i)?'revealed':''}"><strong>${esc(c[0])}</strong>${stateD.revealed.has(i)?`<p>${esc(c[1])}</p>`:`<p class="note">Sealed until inspected.</p><button data-clue="${i}">Inspect</button>`}</div>`).join('')}</div><div class="determination"><h3>Commit before reveal</h3><div class="hypotheses">${hyps.map(h=>`<div class="hypothesis"><label><input type="radio" name="hyp" value="${h[0]}" ${stateD.hyp===h[0]?'checked':''} ${stateD.submitted?'disabled':''}><span><strong>${h[0].toUpperCase()}</strong><br>${esc(h[1])}</span></label></div>`).join('')}</div><label for="mechanism"><strong>Mechanism / reason</strong></label><textarea id="mechanism" rows="4" placeholder="Which evidence relation changed your model, and why?" ${stateD.submitted?'disabled':''}>${esc(stateD.mechanism)}</textarea><div class="controls"><button data-submit-d ${stateD.submitted?'disabled':''}>Seal determination</button><button data-reset-d>New case session</button></div>${result}</div><div class="question"><strong>C1 mechanism question</strong><p>What evidence changed your model of what happened, and why?</p></div><p class="note">Automation proves clue access, hypothesis commit and answer sealing only. C0/C1 human interpretation is still unobserved; earned aha/fairness/causal understanding remain human claims.</p></div>${logHtml(stateD.log)}</section>`}
function bindD(){document.querySelectorAll('[data-clue]').forEach(b=>b.onclick=()=>revealD(Number(b.dataset.clue)));document.querySelector('[data-submit-d]').onclick=submitD;document.querySelector('[data-reset-d]').onclick=()=>{rec('case-reset');stateD=newD();render()}}
const shapes=['circle','square','diamond','bar','ring'];
function newI(){return{pieces:[],selected:null,undo:[],revisions:[],budget:6,log:[{tag:'start',text:'Six-piece budget. Build an artifact, save a revision, then intentionally revise it.'}]}}
function snapshotI(){return JSON.parse(JSON.stringify(stateI.pieces))}
function pushUndo(){stateI.undo.push(snapshotI());if(stateI.undo.length>30)stateI.undo.shift()}
function addPiece(shape){if(stateI.pieces.length>=stateI.budget)return;pushUndo();const id=`p${Date.now()}${Math.floor(Math.random()*99)}`;stateI.pieces.push({id,shape,x:40+stateI.pieces.length*42,y:50+stateI.pieces.length*34,size:64,rot:0});stateI.selected=id;stateI.log.push({tag:'compose',text:`Added ${shape}. Budget ${stateI.pieces.length}/${stateI.budget}.`});rec('piece-add',{shape,count:stateI.pieces.length});render()}
function modPiece(kind){const p=stateI.pieces.find(x=>x.id===stateI.selected);if(!p)return;pushUndo();if(kind==='left')p.x-=16;if(kind==='right')p.x+=16;if(kind==='up')p.y-=16;if(kind==='down')p.y+=16;if(kind==='rotate')p.rot=(p.rot+15)%360;if(kind==='grow')p.size=Math.min(130,p.size+10);if(kind==='shrink')p.size=Math.max(28,p.size-10);p.x=Math.max(0,Math.min(520,p.x));p.y=Math.max(0,Math.min(340,p.y));rec('piece-transform',{kind,id:p.id});render()}
function undoI(){const prev=stateI.undo.pop();if(!prev)return;stateI.pieces=prev;stateI.selected=stateI.pieces.at(-1)?.id||null;rec('undo');render()}
function saveI(){if(!stateI.pieces.length)return;const revision={id:stateI.revisions.length+1,at:new Date().toISOString(),pieces:snapshotI()};stateI.revisions.push(revision);stateI.log.push({tag:`revision ${revision.id}`,text:`Saved ${revision.pieces.length} pieces. Compare intent across revisions; count alone is not value.`});rec('revision-save',{revision:revision.id,pieces:revision.pieces});render()}
function renderI(){const pieces=stateI.pieces.map(p=>`<div data-piece="${p.id}" class="piece shape-${p.shape} ${stateI.selected===p.id?'selected':''}" style="left:${p.x}px;top:${p.y}px;width:${p.size}px;height:${p.size}px;transform:rotate(${p.rot}deg)" title="${p.shape}"></div>`).join('');return `<section class="grid"><div class="panel"><p class="eyebrow">PGP-I · creation / expression · Runtime Agent none</p><h2>Constrained Creation Canvas</h2><p>Compose with a six-piece budget. Presets place only primitives; meaning and revision intent must come from the player.</p><div class="metrics">${metric('pieces',`${stateI.pieces.length}/${stateI.budget}`)}${metric('saved revisions',stateI.revisions.length)}${metric('selected',stateI.selected||'none')}${metric('generator','none')}</div><div class="creation-wrap"><div class="creation-canvas">${pieces}</div><aside><h3>Primitives</h3><div class="palette">${shapes.map(s=>`<button data-add="${s}" ${stateI.pieces.length>=stateI.budget?'disabled':''}>${s}</button>`).join('')}</div><h3>Transform</h3><div class="transform-grid">${['left','up','right','down','rotate','grow','shrink'].map(x=>`<button data-mod="${x}" ${stateI.selected?'':'disabled'}>${x}</button>`).join('')}</div><div class="controls"><button data-undo ${stateI.undo.length?'':'disabled'}>Undo</button><button data-save ${stateI.pieces.length?'':'disabled'}>Save revision</button><button data-reset-i>Clear session</button></div></aside></div><h3>Saved revisions</h3><div class="revisions">${stateI.revisions.map(r=>`<div class="revision"><strong>Revision ${r.id}</strong> · ${r.pieces.length} pieces · ${esc(r.at)}</div>`).join('')||'<p class="note">Save at least two revisions after an intentional change.</p>'}</div><div class="question"><strong>C1 mechanism question</strong><p>What were you trying to make or express, and what did you intentionally change between revisions?</p></div><p class="note">Automation proves compose/transform/undo/save/compare usability only. C0/C1 human authorship evidence is still unobserved; divergent intention and ownership require human evidence.</p></div>${logHtml(stateI.log)}</section>`}
function bindI(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addPiece(b.dataset.add));document.querySelectorAll('[data-piece]').forEach(b=>b.onclick=()=>{stateI.selected=b.dataset.piece;render()});document.querySelectorAll('[data-mod]').forEach(b=>b.onclick=()=>modPiece(b.dataset.mod));document.querySelector('[data-undo]').onclick=undoI;document.querySelector('[data-save]').onclick=saveI;document.querySelector('[data-reset-i]').onclick=()=>{rec('creation-reset');stateI=newI();render()}}
function exportSession(){const payload={...session,participant,exportedAt:new Date().toISOString(),standing:'raw apparatus/player session evidence; C0/C1 standing requires interpretation under GAME_PRE_G0_PLAYABLE_PROOF_PORTFOLIO'};navigator.clipboard?.writeText(JSON.stringify(payload,null,2));const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ordivon-pre-g0-${participant}-${Date.now()}.json`;a.click();URL.revokeObjectURL(a.href)}
function clearEvidence(){if(confirm('Clear local Pre-G0 session evidence?')){session={schemaVersion:1,participant,sessions:[]};persist();render()}}
function render(){window.onkeydown=null;window.onkeyup=null;if(stateA.raf)cancelAnimationFrame(stateA.raf);const body=packet==='A'?renderA():packet==='D'?renderD():renderI();app.innerHTML=`<div class="shell"><header class="hero"><div><p class="eyebrow">Game Pre-G0 · frozen implementation wave</p><h1>Playable Proofs</h1><p>Three bounded apparatuses for unlike Player Value mechanisms. <strong>Prototype completion is not Player Value evidence.</strong></p></div><span class="proof-badge">AUTOMATION ≠ C0/C1</span></header><nav class="tabs">${packets.map(p=>`<button data-packet="${p.id}" class="${packet===p.id?'active':''}"><strong>${p.name}</strong><span>${p.center} · Runtime Agent none</span></button>`).join('')}</nav>${body}<section class="panel session-tools"><p class="eyebrow">evidence boundary</p><div class="participant"><input id="participant" value="${esc(participant)}" aria-label="participant label" placeholder="non-sensitive local participant label"><button data-participant>Set label</button></div><div class="controls"><button data-export>Export local JSON</button><button data-clear>Clear local evidence</button><span class="note">${session.sessions.length} local trace events. No demographics or sensitive data.</span></div></section><section class="guard"><div><strong>Automation</strong>Mechanical route/controls only. No Player Value claim.</div><div><strong>C0</strong>One-human canary. May repair controls/legibility only.</div><div><strong>C1</strong>At least 3 independent sessions across at least 2 humans for individual-play mechanism evidence.</div><div><strong>No ranking</strong>A/D/I cannot eliminate unimplemented B/C/E/F/G/H/J.</div></section></div>`;document.querySelectorAll('[data-packet]').forEach(b=>b.onclick=()=>{packet=b.dataset.packet;rec('packet-open');render()});document.querySelector('[data-participant]').onclick=()=>{participant=(document.querySelector('#participant').value.trim()||'local-c0').slice(0,64);persist();render()};document.querySelector('[data-export]').onclick=exportSession;document.querySelector('[data-clear]').onclick=clearEvidence;if(packet==='A')bindA();if(packet==='D')bindD();if(packet==='I')bindI()}
rec('surface-load',{revision:'wave1-v0.1'});render();
